#137258429 Setup up Heroku instance of CFH
andela/tsunade-cfh pull request #2
Opened 2017-01-10 18:48 UTC by andela-ooyewole

#### What does this PR do?
It aids the deployment of the application to a staging and production server(Heroku), by keeping database access information private for development environments.
#### Description of Task to be completed?
Install and configure 'dotenv' application to manage database authentication.
#### How should this be manually tested?
This is tested by running a cloned and installed copy of this repo and expecting it to fail as a result of the database authentication credentials being undefined, but which when set locally, make the app run successfully.
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
Setup up Heroku instance of CFH
#### Screenshots (if appropriate)
None
#### Questions:
None

2017-01-11 11:35 UTC, q-ode commented on server.js
> +require('dotenv').config();
Let's have this along with all the other modules we already require.

2017-01-11 11:35 UTC, q-ode requested changes
Great Job!

Let's have a `.env.sample` file specifying the environment variables required.

2017-01-12 08:34 UTC, q-ode requested changes
Nice one!

2017-01-12 08:34 UTC, q-ode commented on .env.sample
> +MONGOHQ_URL=<>
Could you put a description for the variable in `<>`.

You wouldn't need the description above. It'll then look like:
`MONGOHG_URL=<URL to MondoDB Database>`

2017-01-12 08:50 UTC, andela-ooyewole commented on .env.sample
> +MONGOHQ_URL=<>
Okay I will do that. Thanks.

2017-01-13 09:45 UTC, q-ode approved these changes

2017-01-13 09:45 UTC, merged